### ISSUE TITLE
Installation depandancie problem

### ISSUE THREAD

**Issue by remsio** [redecheck/redecheck-tool#2]
Hi, 

I'm using windows, and I've tryed to use your application in order to test a website.

But I've got installation problems when I try to install dependencies, I tryed it with eclipse and at the command line: 
![screenshot_13](https://cloud.githubusercontent.com/assets/20771451/25894690/baad9d9e-3574-11e7-9a15-f5947f045df5.png)

I did not find how to resolv it after, here is the debugging report : 
[test.txt](https://github.com/redecheck/redecheck/files/989465/test.txt)

Sorry for asking you here, but your application seems really convenient

Best Regards,
Rémi Matasse

**Comment by twalsh92** [comment]
Hello,

First off, thank you for your interest in ReDeCheck and we’re sorry to hear you’re having trouble getting it to install.

From the error trace you provided, it appears your machine is having trouble connecting to the various maven repositories required to package the tool, hence the various SSL "handshake failure" issues.

From my online research (I personally don't run Windows and haven't for many years), it seems the best bet would be checking that your Maven settings.xml has the correct configuration. This StackOverflow link and Maven docs may help with this:

http://stackoverflow.com/questions/25911623/problems-using-maven-and-ssl-behind-proxy/25912472#25912472

https://maven.apache.org/settings.html

Another less desirable option would be to run Maven without SSL checking, which may resolve the issues and get the tool running for you. The way to do this is discussed in the link below:

http://stackoverflow.com/questions/21252800/how-to-tell-maven-to-disregard-ssl-errors-and-trusting-all-certs?noredirect=1&lq=1


Hopefully these are helpful. Please let me know if the issues persist and we'll do all we can to help solve them.

Kind Regards,

Thomas Walsh
